create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  status text not null check (status in ('pending', 'completed')),
  attachment_url text,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;
